### PR TITLE
Newsweek clone

### PR DESCRIPTION
**Pull request by mariobarrioss**

### CODE REVIEW

**Review by stratospherique — CHANGES_REQUESTED** [review]
> ### Pull request under review by Ahmed Mahfoudh (TSE)

### Splendid work, I liked the style :clap: . However, some changes needs to be made in order for us to approve your project. check :arrow_down: 

- **[REQUIRED]** Check your linter configuration. It doesn't show any checks :red_circle: 
- **[REQUIRED]** Use more semantic HTML elements (e.g. `nav`, `main` and `footer`)
- **[REQUIRED]** Add more info to your readme file and make more descriptive and informative :nerd_face: 

### That's it :relaxed: . When finished, kindly submit another code review request :pray:

**Comment by mariobarrioss** [comment]
@stratospherique Thank you for your feedback. I've implemented the requested changes.

**Comment by ebukaume** [comment]
Hi @mariobarrioss :wave: 

Congratulations. You can now merge this PR.

Status: `Approved!` :champagne: 

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by mariobarrioss** [comment]
@ebukaume Thanks for the review ✌️

**Pull request merged**
